In [1]:
from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import warnings
warnings.simplefilter('ignore')


In [2]:
import numpy as np

3*. Написать свою реализацию метода главных компонент с помощью сингулярного разложения с использованием функции numpy.linalg.svd()

In [3]:
X, y = load_iris(return_X_y=True)
scaler = StandardScaler()

In [4]:
X_scaled = scaler.fit_transform(X)
U, D, V = np.linalg.svd(X_scaled)

In [5]:
D

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [6]:
eig_sum = sum(D)
var_exp = [(i / eig_sum) * 100 for i in D]
cum_var_exp = np.cumsum(var_exp)
print(f'Part of dispersion depicted by each component \n{var_exp}')

Part of dispersion depicted by each component 
[53.529717882362405, 29.95681278402008, 12.003682417209486, 4.509786916408037]


In [7]:
print(f'Cumulative dispersion \n{cum_var_exp}')

Cumulative dispersion 
[ 53.52971788  83.48653067  95.49021308 100.        ]


Leaving 3 features of 4    
Building weight matrix

In [8]:
W = V[:, :3]
W

array([[ 0.52106591, -0.26934744,  0.5804131 ],
       [-0.37741762, -0.92329566, -0.02449161],
       [ 0.71956635, -0.24438178, -0.14212637],
       [ 0.26128628, -0.12350962, -0.80144925]])

In [9]:
X_PCA = X @ W
X_PCA

array([[ 2.39612466, -4.97204318,  2.51511939],
       [ 2.48062028, -4.45652586,  2.41128258],
       [ 2.22896694, -4.56287733,  2.30451427],
       [ 2.35851538, -4.49248937,  2.22049685],
       [ 2.30627631, -5.037438  ,  2.45462892],
       [ 2.66960455, -5.52018213,  2.47651892],
       [ 2.19946209, -4.75739086,  2.14721708],
       [ 2.45371647, -4.87721705,  2.4453146 ],
       [ 2.25782909, -4.22952257,  2.12352519],
       [ 2.48870653, -4.56094264,  2.4747657 ],
       [ 2.54891755, -5.26194472,  2.67013236],
       [ 2.42145992, -4.84778574,  2.31501935],
       [ 2.40238507, -4.41724016,  2.43338619],
       [ 1.9259822 , -4.2092519 ,  2.18581755],
       [ 2.42824872, -5.57335786,  2.93758803],
       [ 2.49330225, -6.01375784,  2.66682231],
       [ 2.38177801, -5.42242942,  2.53336946],
       [ 2.42225329, -4.98439414,  2.43497447],
       [ 2.83753746, -5.49630584,  2.73323693],
       [ 2.38098464, -5.28582102,  2.41341435],
       [ 2.8060561 , -5.03383238,  2.649

4*. Обучить любую модель классификации на датасете iris до применения PCA и после него. Сравнить качество классификации по отложенной выборке.
Загрузка данных, разбиение и стандартизация

In [10]:
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [11]:
scaler = StandardScaler()

In [12]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [14]:
y_pred_train = lr.predict(X_train)
y_pred_test = lr.predict(X_test)

In [15]:
print(accuracy_score(y_train, y_pred_train), accuracy_score(y_test, y_pred_test))

0.9809523809523809 0.9777777777777777


In [16]:
lr_PCA = LogisticRegression()

In [17]:
X_PCAtrain, X_PCAtest, y_train, y_test = train_test_split(X_PCA, y, test_size = 0.3, random_state = 5)

In [18]:
lr_PCA.fit(X_PCAtrain, y_train)

LogisticRegression()

In [19]:
y_pred_train = lr_PCA.predict(X_PCAtrain)
y_pred_test = lr_PCA.predict(X_PCAtest)

In [20]:
print(accuracy_score(y_train, y_pred_train), accuracy_score(y_test, y_pred_test))


0.9714285714285714 0.9555555555555556


**results worse after PCA**